### PR TITLE
Resubmit a submitted or failed job

### LINKED ISSUE #206: Add ability to resubmit simulation.
The workflow:

1. Copy a template. Edit files. Submit job.
2. After job completes, you inspect the output. Open the job script, make a modification and close it. Then click submit again.

A real-world workflow where this is necessary is Truck Sim. Truck Sim's workflow was to submit a job with the steps set to 5000. After the job completed, if you wanted to do more steps, you could change the steps count to 7000 in the script, and submit the job again. It would continue with the existing data that was produced and run the extra 2000 steps.

Of course, "resubmitting" a job is really creating a new batch job with the same script and workdir. osc_machete_rails should already be setup to handle this (creating a new job and showing the status of the workflow as a status of all the jobs).

Submit button then only be disabled when the status was in a running/active state. If not submitted or completed, Submit would be enabled.

For a test case to confirm this works as desired, having access to a version of the Truck Sim simulation where increasing the number of steps might be useful. Summer can help with that.

### PR DESCRIPTION
**Pull request by brianmcmichael**
Resolves #206 

* Re-enables the submit button on inactive jobs
* Clears the existing jobs out of a workflow when an inactive job is submitted, allowing it to be submitted again.

### CODE REVIEW

File: app/assets/javascripts/workflows.js.coffee [hunk 1]
```diff
@@ -161,7 +161,7 @@ $(window).focus ->
     $("#terminal_button").bind('click', false)
 
 @update_submit_button = (id, status_char) ->
-  if id? && !status_char?
+  if id? && status_char != "R" && status_char != "Q"
```
Comment (ericfranz) [inline app/assets/javascripts/workflows.js.coffee]: In active states between not submitted and completed/failed are many. Running and Queued and Suspended and Held etc. Better to enable if completed/failed or not submitted, instead of trying to match against an active state here.

```
&& ((!status_char?) || status_char == "C" || status_char == "F")
```

or this might be clearer

```
if id? && (status_char in [null, "C", "F"])
```

or you write a function `status_not_active(status_char)` that does this.

Comment (ericfranz) [inline app/assets/javascripts/workflows.js.coffee]: or better yet, don't duplicate the knowledge client side. There is already a method `@workflow.active?`. If that is not true then you should be able to resubmit it. So maybe we add an extra boolean attribute to each workflow in the JSON indicating whether its active or not, and use that, instead of checking the status_char.

Do we do this status_char checking anywhere else?

File: app/controllers/workflows_controller.rb [hunk 2]
```diff
@@ -128,6 +128,12 @@ def destroy
   def submit
     set_workflow
 
+    # We want to allow the user to resubmit a job that has been run or failed. This will clear old jobs from
```
Comment (ericfranz) [inline app/controllers/workflows_controller.rb]: Maybe clarify that "this will delete preexisting job records for this workflow" in the comment. Instead of just saying "clear old jobs from a workflow". 

Also, is there a reason why you choose clear over delete_all over destroy_all? Might want to mention that in the comments too.

Comment (brianmcmichael) [inline app/controllers/workflows_controller.rb]: You mean `clear`?

I don't remember why `clear` works and `destroy` doesn't. I'll figure it out again and I may need to put an issue in `osc-machete` or `osc_machete_rails`

```
irb(main):009:0> Workflow.last.jobs
  Workflow Load (5.1ms)  SELECT  "workflows".* FROM "workflows"   ORDER BY "workflows"."id" DESC LIMIT 1
  Job Load (3.7ms)  SELECT "jobs".* FROM "jobs"  WHERE "jobs"."workflow_id" = ?  [["workflow_id", 82]]
=> #<ActiveRecord::Associations::CollectionProxy [#<Job id: 27, workflow_id: 82, status: "Q", job_cache: {"sc
ript"=>"/users/appl/bmcmichael/ondemand/dev/myjobs/data/projects/default/66/pbs_script.sh", "pbsid"=>"9327595
.oak-batch.osc.edu", "host"=>"oakley"}, created_at: "2017-05-19 15:04:21", updated_at: "2017-05-19 15:04:21">
]>
irb(main):010:0> Workflow.last.jobs.destroy
  Workflow Load (3.0ms)  SELECT  "workflows".* FROM "workflows"   ORDER BY "workflows"."id" DESC LIMIT 1
=> []
irb(main):011:0> Workflow.last.submitted?  
  Workflow Load (1.7ms)  SELECT  "workflows".* FROM "workflows"   ORDER BY "workflows"."id" DESC LIMIT 1
  Job Load (1.7ms)  SELECT "jobs".* FROM "jobs"  WHERE "jobs"."workflow_id" = ?  [["workflow_id", 82]]
=> true
irb(main):012:0> Workflow.last.jobs.clear  
  Workflow Load (2.0ms)  SELECT  "workflows".* FROM "workflows"   ORDER BY "workflows"."id" DESC LIMIT 1
  SQL (8.5ms)  DELETE FROM "jobs" WHERE "jobs"."workflow_id" = ?  [["workflow_id", 82]]
=> #<ActiveRecord::Associations::CollectionProxy []>
irb(main):013:0> Workflow.last.submitted?
  Workflow Load (2.0ms)  SELECT  "workflows".* FROM "workflows"   ORDER BY "workflows"."id" DESC LIMIT 1
  Job Load (1.7ms)  SELECT "jobs".* FROM "jobs"  WHERE "jobs"."workflow_id" = ?  [["workflow_id", 82]]
=> false
```

**Comment by brianmcmichael** [comment]
* Updated to use `destroy_all` instead of clear
* Updated to use the `Workflow#active?` method instead of status codes directly
